vich_uploader:
    db_driver: orm

    mappings:
        jeux_images:
            uri_prefix: /images/jeux
            upload_destination: '%kernel.project_dir%/public/images/jeux'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
